worker_processes 2;
pid /tmp/nginx.pid;
error_log /opt/hls-orange/logs/nginx-error.log warn;

events {
    worker_connections 1024;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent"';

    access_log /opt/hls-orange/logs/nginx-access.log main;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;

    gzip on;
    gzip_types text/plain text/css application/json;

    server {
        listen 8008;
        server_name _;

        root /opt/hls-orange/hls;

        add_header Access-Control-Allow-Origin  "*" always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Range" always;
        add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;

        location = /options-preflight {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, OPTIONS";
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Length 0;
            return 204;
        }

        location ~* \.m3u8$ {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
            add_header Content-Type "application/vnd.apple.mpegurl";
            add_header Access-Control-Allow-Origin "*" always;
        }

        location ~* \.ts$ {
            add_header Cache-Control "max-age=10";
            add_header Content-Type "video/MP2T";
            add_header Access-Control-Allow-Origin "*" always;
        }

        location /health {
            return 200 "OK\n";
            add_header Content-Type text/plain;
        }

        location / {
            index index.html;
        }
    }
}
